FROM node:20-alpine
WORKDIR /app

RUN apk add --no-cache docker-cli

COPY package.json package-lock.json* ./
RUN npm install

COPY src ./src
COPY views ./views
COPY public ./public

ENV NODE_ENV=development
EXPOSE 3000

CMD ["npm", "run", "dev"]
